name: Build and Publish bash reminder .deb on Tag creation

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-upload-deb:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Parse the version from the tag
      - name: Parse Version
        run: |
          # Extract version from the TAG
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build .deb package
        run: |
          # Extract version from the TAG
          echo "Building .deb package for version ${{ env.VERSION }}"
          
          # Create necessary directories
          mkdir -p bash-reminder/DEBIAN bash-reminder/usr/bin

          # Control file for the .deb package
          cat <<EOF>> bash-reminder/DEBIAN/control
          Package: bash-reminder
          Version: ${{ env.VERSION }}
          Section: utils
          Priority: optional
          Architecture: all
          Maintainer: Alexandre Lithaud
          Description: A Bash terminal based todo list for developers
          EOF

          # Copy script
          cp ./sh-rem.sh bash-reminder/usr/bin/bash-reminder
          chmod +x bash-reminder/usr/bin/bash-reminder

          # Build the .deb package
          dpkg-deb --build bash-reminder
          mv bash_reminder.deb bash-reminder_v${{ env.VERSION }}.deb

      - name: Create GitHub Release with binary
        uses: softprops/action-gh-release@v2
        with:
          files: bash_reminder.deb bash-reminder_v${{ env.VERSION }}.deb
